"use client";

import { create } from "zustand";
import { persist, createJSONStorage } from "zustand/middleware";

export interface LiturgicalYearEntry {
  /** YYYY-MM-DD (Gregorian) */
  date: string;
  title?: string;
  feast?: string;
  /** Liturgical season label (e.g. "Time after Pentecost"). Used in the dashboard header. */
  season?: string;
  /** Sunday email: commemorated saints listed after the principal Mass header (stripped headlines). */
  commemorations?: string[];
  reflection?: string;
  /** Optional Latin variant of the Reflection (paired with the English `reflection`). */
  reflectionLatin?: string;
  collect?: string;
  /** Optional Latin variant of the Collect (paired with the English `collect`). */
  collectLatin?: string;
  readings?: string;
  /** Optional Latin variant of the Readings (paired with the English `readings`). */
  readingsLatin?: string;
  /** Single-paragraph pull-quote rendered as the main body of the dashboard.
   *  Generated by the LLM at email-arrival time and cached here so the TV
   *  doesn't need to re-call the model on every render. */
  quote?: string;
  /** Original pasted text/HTML for later re-parsing. */
  raw?: string;
  source?: "manual" | "email" | "import";
  updatedAt: string;
}

interface State {
  entries: Record<string, LiturgicalYearEntry>;
  setEntry: (e: Omit<LiturgicalYearEntry, "updatedAt"> & { updatedAt?: string }) => void;
  removeEntry: (date: string) => void;
  importMany: (list: LiturgicalYearEntry[]) => void;
  reset: () => void;
}

export const useLiturgicalYearStore = create<State>()(
  persist(
    (set) => ({
      entries: {},
      setEntry: (e) =>
        set((s) => ({
          entries: {
            ...s.entries,
            [e.date]: { ...e, updatedAt: e.updatedAt ?? new Date().toISOString() },
          },
        })),
      removeEntry: (date) =>
        set((s) => {
          const copy = { ...s.entries };
          delete copy[date];
          return { entries: copy };
        }),
      importMany: (list) =>
        set((s) => {
          const next = { ...s.entries };
          for (const e of list) {
            next[e.date] = { ...e, updatedAt: e.updatedAt ?? new Date().toISOString() };
          }
          return { entries: next };
        }),
      reset: () => set({ entries: {} }),
    }),
    {
      name: "farm-app-liturgical-year",
      storage: createJSONStorage(() => localStorage),
    }
  )
);
